UI in progress...
OpenGeekBrains/SciMaterials pull request #143
Opened 2022-12-07 17:46 UTC by AlexanderMeshchaninov

- Category changes;

2022-12-10 17:51 UTC, Infarh commented
Разобраться в работе изоляции css - см.запись в Телеграм.

2022-12-12 16:32 UTC, AlexanderMeshchaninov commented
Все исправил )

2022-12-13 18:05 UTC, Infarh requested changes

2022-12-13 18:05 UTC, Infarh commented on Services/SciMaterials.Contracts.Identity.API/IIdentityApi.cs
> +/// <summary> �������� ��� Identity </summary>
Беда с кодировкой.

2022-12-13 18:05 UTC, Infarh commented on UI/SciMaterials.UI.MVC/appsettings.json
> +    "Provider": "MySQL.Localhost",
```suggestion
    "Provider": "SqlServer.Debug",

```

2022-12-13 18:05 UTC, Infarh commented on UI/SciMaterials.UI.MVC/appsettings.json
> +    "Provider": "PostgresSQL",
```suggestion
    "Provider": "SQLite",

```

2022-12-13 18:14 UTC, Infarh requested changes

2022-12-13 18:14 UTC, Infarh commented on Services/SciMaterials.Contracts.Identity.API/IIdentityApi.cs
> +/// <summary> �������� ��� Identity </summary>
```suggestion
/// <summary> Контракт апи Identity </summary>
```

2022-12-13 18:15 UTC, Infarh approved these changes

2022-12-13 18:15 UTC, merged